<?php

use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\ReplaceCommand;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function embed_test_form_embed_button_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form_object = $form_state->getFormObject();

  /** @var \Drupal\embed\EmbedButtonInterface $button */
  $button = $form_state->getTemporaryValue('embed_button');

  if ($button->getEmbedType() == 'embed_test_a') {
    $form['third_party_settings']['embed_test_a']['type'] = array(
      '#type' => 'select',
      '#title' => t('Type'),
      '#options' => array(
        'animals' => t('Animals'),
        'airplanes' => t('Airplanes'),
      ),
      '#default_value' => $button->getThirdPartySetting('embed_test_a', 'type'),
      '#required' => TRUE,
      '#ajax' => array(
        'callback' => array(get_class($form_object), 'updateThirdPartySettings'),
        'effect' => 'fade',
      ),
    );

    switch ($form['third_party_settings']['embed_test_a']['type']['#default_value']) {
      case 'animals':
        $form['third_party_settings']['embed_test_a']['subtype'] = array(
          '#type' => 'checkboxes',
          '#title' => t('Subtypes'),
          '#options' => array(
            'amphibians' => t('Amphibians'),
            'birds' => t('Birds'),
            'fish' => t('Fish'),
            'mammals' => t('Mammals'),
            'reptiles' => t('Reptiles'),
          ),
          '#default_value' => $button->getThirdPartySetting('embed_test_a', 'subtype', array()),
        );
        break;
    }
  }

  if ($button->getEmbedType() == 'embed_test_b') {
    $form['third_party_settings']['embed_test_b']['type'] = array(
      '#type' => 'select',
      '#title' => t('Type'),
      '#options' => array('ballads', 'buttons'),
      '#default_value' => $button->getThirdPartySetting('embed_test_b', 'type'),
      '#required' => TRUE,
    );
  }

}
